name: docker-image

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        sh -c 'yes | docker system prune'
        sh -c "docker image ls|grep '<none>'|awk '{ print $3 }'|xargs docker image rm"
        docker build --pull --no-cache . --tag zasdfgbnmsystem/basic
    - name: Publish the Docker image
      run: |
        docker login -u zasdfgbnm -p ${{secrets.zasdfgbnm_bot_dockerhub_password}}
        docker push zasdfgbnmsystem/basic
